### ISSUE TITLE
HTML Special characters

### ISSUE THREAD

**Issue by martoio** [faris-d/prj-rev-bwfs-dasmoto#1]
Check out this article that explains why you need to care about using special characters in HTML: http://text-symbols.com/html/encode/

https://github.com/faris-d/prj-rev-bwfs-dasmoto/blob/fddcafd66ab9c283ae3e6cb4c5850abb63e379bd/arts%26crafts/index.html#L7

The ampersand should be written as:
``&amp;``

**Comment by faris-d** [comment]
Yes, thanks! I noticed that the & was appearing in a different color ... This clarifies why.
