### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by martoio** [faris-d/prj-rev-bwfs-dasmoto#3]
Make sure you add the ``alt`` attribute to your images to maintain accessibility for all audiences of the page (particularly visually-impaired users). Remember to add it even in these simple projects and it will become a habit. (Hint: as long as you have the ``alt`` attribute with something semi-meaningful, we'll be happy with it).
For more info: https://www.codecademy.com/articles/accessibility

https://github.com/faris-d/prj-rev-bwfs-dasmoto/blob/fddcafd66ab9c283ae3e6cb4c5850abb63e379bd/arts%26crafts/index.html#L13

**Comment by faris-d** [comment]
Will definitely keep that in mind. Thank you!
